//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zengamemanifesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSet
    {
        public int Id { get; set; }
        public string BookTitle { get; set; }
        public string ImgUrl { get; set; }
        public string BuyUrl { get; set; }
        public string PreviewUrl { get; set; }
        public string AboutText { get; set; }
        public string Price { get; set; }
    }
}
