//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zengamemanifesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSet
    {
        public UserSet()
        {
            this.BookSet = new HashSet<BookSet>();
            this.StartPagePostsSet = new HashSet<StartPagePostsSet>();
            this.VideoSet = new HashSet<VideoSet>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordHash { get; set; }
    
        public virtual ICollection<BookSet> BookSet { get; set; }
        public virtual ICollection<StartPagePostsSet> StartPagePostsSet { get; set; }
        public virtual ICollection<VideoSet> VideoSet { get; set; }
    }
}
